version: '3'
services:
  api:
    container_name: comment_api
    build:
      context: ./
      dockerfile: ./infrastructure/dev/Dockerfile
    image: commentapi:latest
    ports:
      - "8080:80"
    expose:
      - '80'
    volumes:
      - ./:/var/www/html
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    depends_on:
      - database
    env_file:
      - .env

  database:
    container_name: comment_db
    image: mysql:5.7.19
    restart: always
    environment:
      - MYSQL_DATABASE=comment
      - MYSQL_USER=commentuser
      - MYSQL_PASSWORD=commentpass
      - MYSQL_ROOT_PASSWORD=commentsecret
    ports:
      - '3306'
    expose:
      - '3306'

